import os
import pycountry
import shutil

# Define the mapping for ISO codes to country names in French
country_names_fr = {
    'AF': 'Afghanistan',
    'AX': 'Îles Åland',
    'AL': 'Albanie',
    'DZ': 'Algérie',
    'AS': 'Samoa américaines',
    'AD': 'Andorre',
    'AO': 'Angola',
    'AI': 'Anguilla',
    'AQ': 'Antarctique',
    'AG': 'Antigua-et-Barbuda',
    'AR': 'Argentine',
    'AM': 'Arménie',
    'AW': 'Aruba',
    'AU': 'Australie',
    'AT': 'Autriche',
    'AZ': 'Azerbaïdjan',
    'BS': 'Bahamas',
    'BH': 'Bahreïn',
    'BD': 'Bangladesh',
    'BB': 'Barbade',
    'BY': 'Bélarus',
    'BE': 'Belgique',
    'BZ': 'Belize',
    'BJ': 'Bénin',
    'BM': 'Bermudes',
    'BT': 'Bhoutan',
    'BO': 'Bolivie',
    'BQ': 'Bonaire, Saint-Eustache et Saba',
    'BA': 'Bosnie-Herzégovine',
    'BW': 'Botswana',
    'BV': 'Île Bouvet',
    'BR': 'Brésil',
    'IO': 'Territoire britannique de l\'océan Indien',
    'BN': 'Brunei Darussalam',
    'BG': 'Bulgarie',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'CV': 'Cabo Verde',
    'KH': 'Cambodge',
    'CM': 'Cameroun',
    'CA': 'Canada',
    'KY': 'Îles Caïmans',
    'CF': 'République centrafricaine',
    'TD': 'Tchad',
    'CL': 'Chili',
    'CN': 'Chine',
    'CX': 'Île Christmas',
    'CC': 'Îles Cocos (Keeling)',
    'CO': 'Colombie',
    'KM': 'Comores',
    'CG': 'Congo',
    'CD': 'Congo (RDC)',
    'CK': 'Îles Cook',
    'CR': 'Costa Rica',
    'HR': 'Croatie',
    'CU': 'Cuba',
    'CW': 'Curaçao',
    'CY': 'Chypre',
    'CZ': 'Tchéquie',
    'DK': 'Danemark',
    'DJ': 'Djibouti',
    'DM': 'Dominique',
    'DO': 'République dominicaine',
    'EC': 'Équateur',
    'EG': 'Égypte',
    'SV': 'El Salvador',
    'GQ': 'Guinée équatoriale',
    'ER': 'Érythrée',
    'EE': 'Estonie',
    'SZ': 'Eswatini',
    'ET': 'Éthiopie',
    'FK': 'Îles Malouines',
    'FO': 'Îles Féroé',
    'FJ': 'Fidji',
    'FI': 'Finlande',
    'FR': 'France',
    'GF': 'Guyane française',
    'PF': 'Polynésie française',
    'TF': 'Terres australes françaises',
    'GA': 'Gabon',
    'GM': 'Gambie',
    'GE': 'Géorgie',
    'DE': 'Allemagne',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GR': 'Grèce',
    'GL': 'Groenland',
    'GD': 'Grenade',
    'GP': 'Guadeloupe',
    'GU': 'Guam',
    'GT': 'Guatemala',
    'GG': 'Guernesey',
    'GN': 'Guinée',
    'GW': 'Guinée-Bissau',
    'GY': 'Guyana',
    'HT': 'Haïti',
    'HM': 'Îles Heard et McDonald',
    'VA': 'Saint-Siège (État de la Cité du Vatican)',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hongrie',
    'IS': 'Islande',
    'IN': 'Inde',
    'ID': 'Indonésie',
    'IR': 'Iran',
    'IQ': 'Irak',
    'IE': 'Irlande',
    'IM': 'Île de Man',
    'IL': 'Israël',
    'IT': 'Italie',
    'JM': 'Jamaïque',
    'JP': 'Japon',
    'JE': 'Jersey',
    'JO': 'Jordanie',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'KP': 'Corée (Rép. pop.)',
    'KR': 'Corée (Rép.)',
    'KW': 'Koweït',
    'KG': 'Kirghizistan',
    'LA': 'Laos',
    'LV': 'Lettonie',
    'LB': 'Liban',
    'LS': 'Lesotho',
    'LR': 'Libéria',
    'LY': 'Libye',
    'LI': 'Liechtenstein',
    'LT': 'Lituanie',
    'LU': 'Luxembourg',
    'MO': 'Macao',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaisie',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malte',
    'MH': 'Îles Marshall',
    'MQ': 'Martinique',
    'MR': 'Mauritanie',
    'MU': 'Maurice',
    'YT': 'Mayotte',
    'MX': 'Mexique',
    'FM': 'Micronésie',
    'MD': 'Moldavie',
    'MC': 'Monaco',
    'MN': 'Mongolie',
    'ME': 'Monténégro',
    'MS': 'Montserrat',
    'MA': 'Maroc',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibie',
    'NR': 'Nauru',
    'NP': 'Népal',
    'NL': 'Pays-Bas',
    'NC': 'Nouvelle-Calédonie',
    'NZ': 'Nouvelle-Zélande',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigéria',
    'NU': 'Niue',
    'NF': 'Île Norfolk',
    'MK': 'Macédoine (Rép.)',
    'MP': 'Îles Mariannes du Nord',
    'NO': 'Norvège',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palaos',
    'PS': 'Palestine, État de',
    'PA': 'Panama',
    'PG': 'Papouasie-Nouvelle-Guinée',
    'PY': 'Paraguay',
    'PE': 'Pérou',
    'PH': 'Philippines',
    'PN': 'Pitcairn',
    'PL': 'Pologne',
    'PT': 'Portugal',
    'PR': 'Porto Rico',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Roumanie',
    'RU': 'Russie',
    'RW': 'Rwanda',
    'BL': 'Saint-Barthélemy',
    'SH': 'Sainte-Hélène',
    'KN': 'Saint-Kitts-et-Nevis',
    'LC': 'Sainte-Lucie',
    'MF': 'Saint-Martin (partie française)',
    'PM': 'Saint-Pierre-et-Miquelon',
    'VC': 'Saint-Vincent-et-les-Grenadines',
    'WS': 'Samoa',
    'SM': 'Saint-Marin',
    'ST': 'Sao Tomé-et-Principe',
    'SA': 'Arabie saoudite',
    'SN': 'Sénégal',
    'RS': 'Serbie',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapour',
    'SX': 'Saint-Martin (partie néerlandaise)',
    'SK': 'Slovaquie',
    'SI': 'Slovénie',
    'SB': 'Îles Salomon',
    'SO': 'Somalie',
    'ZA': 'Afrique du Sud',
    'GS': 'Géorgie du Sud et îles Sandwich du Sud',
    'SS': 'Soudan du Sud',
    'ES': 'Espagne',
    'LK': 'Sri Lanka',
    'SD': 'Soudan',
    'SR': 'Suriname',
    'SJ': 'Svalbard et Jan Mayen',
    'SE': 'Suède',
    'CH': 'Suisse',
    'SY': 'Syrie',
    'TW': 'Taïwan',
    'TJ': 'Tadjikistan',
    'TZ': 'Tanzanie',
    'TH': 'Thaïlande',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TK': 'Tokelau',
    'TO': 'Tonga',
    'TT': 'Trinité-et-Tobago',
    'TN': 'Tunisie',
    'TR': 'Turquie',
    'TM': 'Turkménistan',
    'TC': 'Îles Turks-et-Caïcos',
    'TV': 'Tuvalu',
    'UG': 'Ouganda',
    'UA': 'Ukraine',
    'AE': 'Émirats arabes unis',
    'GB': 'Royaume-Uni',
    'UM': 'Îles mineures éloignées des États-Unis',
    'US': 'États-Unis',
    'UY': 'Uruguay',
    'UZ': 'Ouzbékistan',
    'VU': 'Vanuatu',
    'VE': 'Venezuela',
    'VN': 'Viêt Nam',
    'VG': 'Îles Vierges britanniques',
    'VI': 'Îles Vierges des États-Unis',
    'WF': 'Wallis-et-Futuna',
    'EH': 'Sahara occidental',
    'YE': 'Yémen',
    'ZM': 'Zambie',
    'ZW': 'Zimbabwe',
    'GB-ENG': 'Angleterre',
    'GB-NIR': 'Irlande du Nord',
    'GB-SCT': 'Écosse',
    'GB-WLS': 'Pays de Galles',
    'XK': 'Kosovo'
}

# Directory paths
extracted_dir = '../w2560'  # Replace with the actual path
renamed_dir = '../flags2'  # Replace with the actual path
os.makedirs(renamed_dir, exist_ok=True)

# Function to rename files
def rename_files(directory, rename_map):
    for old_name in os.listdir(directory):
        code = old_name.split('.')[0].upper()
        if code in rename_map:
            new_name = rename_map[code] + '.png'
            old_path = os.path.join(directory, old_name)
            new_path = os.path.join(directory, new_name)
            shutil.copy(old_path, new_path)

# Apply renaming
rename_files(extracted_dir, country_names_fr)

print("Files renamed successfully.")
